int size(string );
bool goToRegion();
char to_upper(char );
string toUpWord(string );
bool stob(string);
int size();
bool isBig(string, string);
void toStr(string a, int*, int*, int*);
void addFile(string , string , int );
string printStars(hotelInfo);
int checkRoomCount(string , string , checkinUser );
